spring:
  datasource:
    url: jdbc:h2:mem:dsin
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Chave secreta para assinatura JWT
      expiration: 86400000
      refresh-token:
        expiration: 604800000
